version: '3.8'

# Development compose file
# This is now used for local development with SQLite
# Run: docker compose -f docker-compose.dev.yaml up

services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: better-plan-app-dev
    ports:
    - "3000:3000"
    environment:
    # --- Local SQLite database for development
    - DATABASE_URL=file:///app/data/dev.db
    - DATABASE_AUTH_TOKEN=
    - DATABASE_DIALECT=sqlite
    - NODE_ENV=development
    # --- Other application variables
    - APP_URL=${APP_URL:-http://localhost:3000}
    - X_CLIENT_ID=${X_CLIENT_ID}
    - X_CLIENT_SECRET=${X_CLIENT_SECRET}
    - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET:-dev-secret-key-change-in-production}
    - DISABLE_SIGNUP=${DISABLE_SIGNUP:-false}
    volumes:
    # --- Persistent volume for development SQLite database
    - sqlite_data_dev:/app/data
    # --- Mount source code for development (if needed)
    # - .:/app
    restart: unless-stopped

volumes:
  sqlite_data_dev:
