networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: better-plan-app
    ports:
    - "3000:3000"
    environment:
    # --- Database connection (Turso or local SQLite)
    - DATABASE_URL=${DATABASE_URL:-file:///app/data/local.db}
    - DATABASE_AUTH_TOKEN=${DATABASE_AUTH_TOKEN:-}
    - DATABASE_DIALECT=${DATABASE_DIALECT:-sqlite}
    # --- Other application variables
    - APP_URL=${APP_URL}
    - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
    - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    - X_CLIENT_ID=${X_CLIENT_ID}
    - X_CLIENT_SECRET=${X_CLIENT_SECRET}
    - REDDIT_CLIENT_ID=${REDDIT_CLIENT_ID}
    - REDDIT_CLIENT_SECRET=${REDDIT_CLIENT_SECRET}
    - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
    - DISABLE_SIGNUP=${DISABLE_SIGNUP}
    - NODE_ENV=${NODE_ENV:-production}
    # --- AI Configuration
    - OPENAI_API_KEY=${OPENAI_API_KEY}
    - DEPLOYMENT_TYPE=${DEPLOYMENT_TYPE:-self-hosted}
    - AI_MAX_CONTEXT_WINDOW=${AI_MAX_CONTEXT_WINDOW:-4000}
    - AI_MAX_GENERATIONS_PER_MONTH=${AI_MAX_GENERATIONS_PER_MONTH:-50}
    - AI_MODEL=${AI_MODEL:-gpt-4o-mini}
    # --- Plausible Analytics
    - VITE_PLAUSIBLE_DOMAIN=${VITE_PLAUSIBLE_DOMAIN}
    - VITE_PLAUSIBLE_SCRIPT_URL=${VITE_PLAUSIBLE_SCRIPT_URL}
    volumes:
    # --- Volume for local SQLite database (when not using Turso)
    - sqlite_data:/app/data
    restart: unless-stopped
    networks:
    - app-network

volumes:
  sqlite_data:
