
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    # --- Connection details for PostgreSQL
    - POSTGRES_USER=${SERVICE_USER_POSTGRES}
    - POSTGRES_PASSWORD=${SERVICE_PASSWORD_POSTGRES}
    - POSTGRES_DB=${POSTGRES_DB:-better_plan_db}
    - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    # --- Host override for Docker's internal network
    - POSTGRES_HOST=postgres
    # --- Other application variables
    - APP_URL=${SERVICE_FQDN_APP}
    - X_CLIENT_ID=${X_CLIENT_ID}
    - X_CLIENT_SECRET=${X_CLIENT_SECRET}
    - BETTER_AUTH_SECRET=${SERVICE_PASSWORD_AUTH}
    - DISABLE_SIGNUP=${DISABLE_SIGNUP:-false}
    depends_on:
    - postgres

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${SERVICE_USER_POSTGRES}
      POSTGRES_PASSWORD: ${SERVICE_PASSWORD_POSTGRES}
      POSTGRES_DB: ${POSTGRES_DB:-better_plan_db}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
    volumes:
    - postgres_data:/var/lib/postgresql/data
