networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: better-plan-app
    ports:
    - "3000:3000"
    environment:
    # --- Database connection (Turso or local SQLite)
    - DATABASE_URL=${DATABASE_URL:-file:///app/data/local.db}
    - DATABASE_AUTH_TOKEN=${DATABASE_AUTH_TOKEN:-}
    - DATABASE_DIALECT=${DATABASE_DIALECT:-sqlite}
    # --- Other application variables
    - APP_URL=${APP_URL}
    - X_CLIENT_ID=${X_CLIENT_ID}
    - X_CLIENT_SECRET=${X_CLIENT_SECRET}
    - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
    - DISABLE_SIGNUP=${DISABLE_SIGNUP}
    - NODE_ENV=${NODE_ENV:-production}
    volumes:
    # --- Volume for local SQLite database (when not using Turso)
    - sqlite_data:/app/data
    restart: unless-stopped
    networks:
    - app-network

volumes:
  sqlite_data:
