
# Coolify deployment configuration
# This configuration is for production deployment using Turso as database

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    # --- Turso database connection (set in Coolify dashboard)
    - DATABASE_URL=${DATABASE_URL}
    - DATABASE_AUTH_TOKEN=${DATABASE_AUTH_TOKEN}
    - DATABASE_DIALECT=${DATABASE_DIALECT:-turso}
    - NODE_ENV=${NODE_ENV:-production}
    # --- Other application variables
    - APP_URL=${APP_URL}
    - X_CLIENT_ID=${X_CLIENT_ID}
    - X_CLIENT_SECRET=${X_CLIENT_SECRET}
    - BETTER_AUTH_SECRET=${SERVICE_PASSWORD_AUTH}
    - DISABLE_SIGNUP=${DISABLE_SIGNUP:-false}
    # --- AI Configuration
    - OPENAI_API_KEY=${OPENAI_API_KEY}
    - DEPLOYMENT_TYPE=${DEPLOYMENT_TYPE:-saas}
    - AI_MAX_CONTEXT_WINDOW=${AI_MAX_CONTEXT_WINDOW:-4000}
    - AI_MAX_GENERATIONS_PER_MONTH=${AI_MAX_GENERATIONS_PER_MONTH:-50}
    - AI_MODEL=${AI_MODEL:-gpt-4o-mini}
