version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: better-plan-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: better-plan
    ports:
    - "5432:5432"
    volumes:
    - postgres_data_dev:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data_dev:
